### ISSUE TITLE
add repo

### ISSUE THREAD

**Issue by nasservb** [laravel98developer/laravel-hiring-projects#1]
Could you please add this repo :
https://github.com/nasservb/AgencyAssistant
it's the Cafebazaar Backend project.

**Comment by nasservb** [comment]
and also this for the German Company: 
https://github.com/nasservb/WorldTravel

**Comment by laravel98developer** [comment]
Hello Dear @nasservb

I appreciate your passion for the betterment of the community.🌹
Since this is a repository for Laravel framework tasks, I'm so sorry to add your projects to this repo.🙏
But if you write a Laravel task for any company, I will happily add it to this repository.

you're stars of the community ⭐️

**Comment by nasservb** [comment]
Thank you so much, 
You could consider this one i developed for one of the European company:
https://github.com/nasservb/crud-test-laravel10
This one is developed for the German company worked on wordpress vulnerability:
https://github.com/nasservb/Vulnerability
And also this one is the Test-driven-development challenge i passed for another German company, They removed the code directory and must be implemented that just by reading the tests. 
https://github.com/nasservb/laravel-tdd-challenge

**Comment by laravel98developer** [comment]
Can you tell me the name of the company that requested this https://github.com/nasservb/crud-test-laravel10?

I think this https://github.com/nasservb/laravel-tdd-challenge is too old! But, I liked their task method! How does it come to their mind?!!! 😅

I welcome you with PR for these projects. If you want to be anonymous, I will add those.
Keep me posted.
