### ISSUE TITLE
رابطه بین تگ و دسته بندی

### ISSUE THREAD

**Issue by mr-mr7** [laravel98developer/laravel-hiring-projects#4]
سلام
نوشته هر تگ یک دسته دارد
ولی بر اساس ساختار تعریفی شما هر تگ میتونه چندین دسته داشته باشه ک اشتباهه 
ساختار مایگریشن 
و درستش این بود که دسته داخل جدول قرار داده بشه نه جدول واسط 🌹

البته در ادامه سوال گفته هر تگ معتلق یه ۲ تا ۸ دسته باشه که فرض اولش که گفته هر تگ میتونه یه دسته داشته باشه تناقض داره به نظرم

**Comment by laravel98developer** [comment]
سلام مهندس جان @mr-mr7 
کدوم تسک رو میفرمایید؟
